In [2]:
import numpy as np

# Array creation


1. Create a numpy array of size 10, filled with zeros


In [4]:

zeros_array = np.zeros(10)

print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Create a numpy array with values ranging from 10 to 49 and set its datatype to float


In [9]:
float_array = np.arange(10, 50, dtype=float)

print(float_array)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


3. Create a numpy matrix of 2*2 integers, filled with ones.



In [10]:
ones_matrix = np.ones((2, 2), dtype=int)

print(ones_matrix)

[[1 1]
 [1 1]]


4. Create a numpy matrix of 3*2 float numbers, filled with ones.

In [11]:
ones_float_matrix = np.ones((3, 2), dtype=float)

print(ones_float_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


5. Given the X numpy array, create a new numpy array with the same shape and type as X,
filled with ones. (#hint: search the function np.ones_like( ) )

In [13]:
X = np.array([[1, 2, 3], [4, 5, 6]])

ones_like_X = np.ones_like(X)

print(ones_like_X)

[[1 1 1]
 [1 1 1]]


6. Given the X numpy matrix, create a new numpy matrix with the same shape and type as
X, filled with zeros. (hint: similar function as above exists for zeros as well)

In [1]:

X = np.array([[1, 2, 3], [4, 5, 6]])  # Example input numpy matrix

new_matrix = np.zeros_like(X)  # Create a new numpy matrix with the same shape and type as X, filled with zeros

print(new_matrix)

[[0 0 0]
 [0 0 0]]


7. Create a numpy matrix of 4*4 integers, filled with fives.

In [2]:

matrix = np.ones((4, 4), dtype=int) * 5

print(matrix)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


8. Given the X numpy matrix, create a new numpy matrix with the same shape and type as
X, filled with sevens.

In [4]:

X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8 , 9]])

new_matrix = np.full_like(X, 7)

print(new_matrix)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


9. Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [5]:

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


10. Create a numpy array, filled with 3 random integer values between 1 and 10.

In [9]:

random_array = np.random.randint(1,10, 3)

print(random_array)

[2 2 8]


11. Create a 3*3*3 numpy matrix, filled with random float values.

In [10]:

random_matrix = np.random.rand(3, 3, 3)

print(random_matrix)

[[[0.45781587 0.44921476 0.59355152]
  [0.02640467 0.05345763 0.523052  ]
  [0.84537363 0.1575867  0.54517551]]

 [[0.73280297 0.99296856 0.8421209 ]
  [0.74152819 0.75394044 0.16440536]
  [0.17277065 0.35191368 0.05299967]]

 [[0.55216443 0.53396774 0.65466119]
  [0.54881216 0.24879212 0.19671517]
  [0.23782049 0.68586918 0.15160369]]]


12. Create a numpy array with numbers from 1 to 10

In [11]:

array = np.arange(1, 11)

print(array)

[ 1  2  3  4  5  6  7  8  9 10]


13. Create a numpy array with the odd numbers between 1 to 10

In [16]:

array = np.arange(1, 11) 
odd_array = array[array %2 != 0] 

print(odd_array)

[1 3 5 7 9]


14. Create a numpy array with numbers from 1 to 10, in descending order.

In [19]:

descending_array = np.array(list(range(10, 0, -1)))

print(descending_array)

[10  9  8  7  6  5  4  3  2  1]


15. Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [20]:
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Array indexing:

1. Given the X numpy array, show its first element X = np.array(['A', 'B', 'C', 'D', 'E'])


In [32]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

first_element = X[0]

print(first_element)

A


2. Given the X numpy array, show its last element X = np.array(['A', 'B', 'C', 'D', 'E'])


In [33]:
last_element = X[-1]

print(last_element)

E


3. Given the X numpy array, show its first three elements

In [34]:
first_three_elements = X[:3]

print(first_three_elements)

['A' 'B' 'C']


4. Given the X numpy array, show all middle elements

In [35]:
middle_elements = X[1:-1]

print(middle_elements)

['B' 'C' 'D']


5. Given the X numpy array, show the elements in reverse position.

In [36]:
reverse_elements = X[::-1]

print(reverse_elements)

['E' 'D' 'C' 'B' 'A']


6. Given the X numpy array, show the elements in an odd position.

In [37]:
odd_elements = X[1::2]
print(odd_elements)

['B' 'D']


7. Given the X numpy matrix, show the first row’s elements.
X1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])


In [43]:
X1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
first_row_elements = X1[0, :]

print(first_row_elements)

[1 2 3 4]


8. Given the X numpy matrix, show the last row elements.


In [44]:
last_row_elements = X1[-1, :]

print(last_row_elements)

[13 14 15 16]


9. Given the X numpy matrix, show the first element on first row

In [45]:
first_element_first_row = X1[0, 0]

print(first_element_first_row)

1


10. Given the X numpy matrix, show the last element on last row.

In [46]:
last_element_last_row = X1[-1, -1]

print(last_element_last_row)

16


11. Given the X numpy matrix, show the first two elements on the first two rows.

In [47]:
first_two_elements_first_two_rows = X1[:2, :2]

print(first_two_elements_first_two_rows)

[[1 2]
 [5 6]]


12. Given the X numpy matrix, show the last two elements on the last two rows

In [48]:
last_two_elements_last_two_rows = X1[-2:, -2:]

print(last_two_elements_last_two_rows)

[[11 12]
 [15 16]]


# Array manipulation

Convert the given integer numpy array to float (you need to google the function that will
help you do this) X = [-5, -3, 0, 10, 40]

In [54]:
X2 = np.array([-5, -3, 0, 10, 40])
X_float = X2.astype(float)

print(X_float)

[-5. -3.  0. 10. 40.]


Reverse the given numpy array (first element becomes last) through indexing X = [-5, -3, 0, 10, 40]

In [55]:
reversed_X = X2[::-1]

print(reversed_X)

[40 10  0 -3 -5]


Given the X numpy array, set the fifth element equal to 1 X = np.zeros(10)

In [56]:
X3 = np.zeros(10)

X3[4] = 1

print(X3)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Given the X numpy matrix, change the last row with all 1
X = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])

In [57]:
X4 = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
]) 
X4[-1, :] = 1

print(X4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


5. Given the X numpy matrix, add 5 to every element
X = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])

In [60]:
X5 = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
X5 += 5

print(X5)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
